import { Camera } from '@api/camera'

const camera = new Camera()
await camera.connect()

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))
const results: Array<{prop: string, set: string, got: any}> = []

// Test aperture formats
await camera.setDeviceProperty('APERTURE', '2.8')
results.push({prop: 'APERTURE', set: '2.8', got: await camera.getDeviceProperty('APERTURE')})
await delay(500)
await camera.setDeviceProperty('APERTURE', 'f/4')
results.push({prop: 'APERTURE', set: 'f/4', got: await camera.getDeviceProperty('APERTURE')})
await delay(500)
await camera.setDeviceProperty('APERTURE', 'f5.6')
results.push({prop: 'APERTURE', set: 'f5.6', got: await camera.getDeviceProperty('APERTURE')})
await delay(500)
await camera.setDeviceProperty('APERTURE', 'f 8')
results.push({prop: 'APERTURE', set: 'f 8', got: await camera.getDeviceProperty('APERTURE')})
await delay(500)
await camera.setDeviceProperty('APERTURE', 'ƒ/11')
results.push({prop: 'APERTURE', set: 'ƒ/11', got: await camera.getDeviceProperty('APERTURE')})
await delay(500)
await camera.setDeviceProperty('APERTURE', 'F:16')
results.push({prop: 'APERTURE', set: 'F:16', got: await camera.getDeviceProperty('APERTURE')})
await delay(500)
await camera.setDeviceProperty('APERTURE', '22')
results.push({prop: 'APERTURE', set: '22', got: await camera.getDeviceProperty('APERTURE')})
await delay(500)

// Test ISO formats
await camera.setDeviceProperty('ISO', '100')
results.push({prop: 'ISO', set: '100', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', 'ISO 200')
results.push({prop: 'ISO', set: 'ISO 200', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', 'ISO400')
results.push({prop: 'ISO', set: 'ISO400', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', '00800')
results.push({prop: 'ISO', set: '00800', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', '01600')
results.push({prop: 'ISO', set: '01600', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', 'auto')
results.push({prop: 'ISO', set: 'auto', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', 'Auto')
results.push({prop: 'ISO', set: 'Auto', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', 'ISO AUTO')
results.push({prop: 'ISO', set: 'ISO AUTO', got: await camera.getDeviceProperty('ISO')})
await delay(500)
await camera.setDeviceProperty('ISO', '3200')
results.push({prop: 'ISO', set: '3200', got: await camera.getDeviceProperty('ISO')})
await delay(500)

// Test shutter speed formats
await camera.setDeviceProperty('SHUTTER_SPEED', '30')
results.push({prop: 'SHUTTER_SPEED', set: '30', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '15s')
results.push({prop: 'SHUTTER_SPEED', set: '15s', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '8"')
results.push({prop: 'SHUTTER_SPEED', set: '8"', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', "4'")
results.push({prop: 'SHUTTER_SPEED', set: "4'", got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '2sec')
results.push({prop: 'SHUTTER_SPEED', set: '2sec', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1 seconds')
results.push({prop: 'SHUTTER_SPEED', set: '1 seconds', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/2')
results.push({prop: 'SHUTTER_SPEED', set: '1/2', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/4s')
results.push({prop: 'SHUTTER_SPEED', set: '1/4s', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/8')
results.push({prop: 'SHUTTER_SPEED', set: '1/8', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/15')
results.push({prop: 'SHUTTER_SPEED', set: '1/15', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/30')
results.push({prop: 'SHUTTER_SPEED', set: '1/30', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/60')
results.push({prop: 'SHUTTER_SPEED', set: '1/60', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/125')
results.push({prop: 'SHUTTER_SPEED', set: '1/125', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/250')
results.push({prop: 'SHUTTER_SPEED', set: '1/250', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/500')
results.push({prop: 'SHUTTER_SPEED', set: '1/500', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/1000')
results.push({prop: 'SHUTTER_SPEED', set: '1/1000', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/2000')
results.push({prop: 'SHUTTER_SPEED', set: '1/2000', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/4000')
results.push({prop: 'SHUTTER_SPEED', set: '1/4000', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '1/8000')
results.push({prop: 'SHUTTER_SPEED', set: '1/8000', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '0.5"')
results.push({prop: 'SHUTTER_SPEED', set: '0.5"', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '0.25')
results.push({prop: 'SHUTTER_SPEED', set: '0.25', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', '2.5"')
results.push({prop: 'SHUTTER_SPEED', set: '2.5"', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', 'bulb')
results.push({prop: 'SHUTTER_SPEED', set: 'bulb', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', 'BULB')
results.push({prop: 'SHUTTER_SPEED', set: 'BULB', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', 'b')
results.push({prop: 'SHUTTER_SPEED', set: 'b', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)
await camera.setDeviceProperty('SHUTTER_SPEED', 'B')
results.push({prop: 'SHUTTER_SPEED', set: 'B', got: await camera.getDeviceProperty('SHUTTER_SPEED')})
await delay(500)

await camera.disconnect()

// Log all results
console.log('\nTest Results:')
console.log('=============\n')
results.forEach(r => {
  console.log(`${r.prop}: Set "${r.set}" → Got "${r.got}"`)
})

process.exit(0)
